tap "jandedobbeleer/oh-my-posh"
tap "shivammathur/php", trusted: true
# General-purpose scripting language
brew "php", restart_service: :changed
# Dependency Manager for PHP
brew "composer"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Open source relational database management system
brew "mysql"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx", restart_service: :changed
# Manage multiple Node.js versions
brew "nvm"
# AI coding agent, built for the terminal
brew "opencode"
# PHP Installer for Extensions
brew "pie"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Object-relational database system
brew "postgresql@18", link: true
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Prompt theme engine for any shell
brew "jandedobbeleer/oh-my-posh/oh-my-posh", trusted: true
# General-purpose scripting language
brew "shivammathur/php/php@7.4", trusted: true
# Allows connection to a computer remotely
cask "anydesk"
# Web browser focusing on privacy
cask "brave-browser"
# Open source IDE for exploring and testing APIs
cask "bruno"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-geist-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Web browser
cask "google-chrome"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Get up and running with large language models locally
cask "ollama-app"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Peer to peer Bitorrent client
cask "qbittorrent"
# System monitor for the menu bar
cask "stats"
# Native GUI tool for relational databases
cask "tableplus"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
vscode "bmewburn.vscode-intelephense-client"
vscode "bradlc.vscode-tailwindcss"
vscode "damms005.devdb"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "devsense.composer-php-vscode"
vscode "devsense.profiler-php-vscode"
vscode "dnicolson.binary-plist"
vscode "docker.docker"
vscode "editorconfig.editorconfig"
vscode "formulahendry.auto-rename-tag"
vscode "georgykurian.laravel-ide-helper"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "laravel.vscode-laravel"
vscode "mechatroner.rainbow-csv"
vscode "mehedidracula.php-namespace-resolver"
vscode "mkhl.shfmt"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vsliveshare.vsliveshare"
vscode "ollama.ollama"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "timonwong.shellcheck"
vscode "viktorqvarfordt.vscode-pitch-black-theme"
vscode "xdebug.php-debug"
npm "eslint"
